- hosts: all
  become: yes
  become_user: root
  gather_facts: no

  tasks:
  - name: Delete PD snapshots
    local_action: command python delete_pd_snapshots.py --user {{ user }} --passwd {{ passwd }} --pgip {{ pgip }} --pdname {{ pdname }}
    register: pdout
    run_once: true
  - debug: msg="Protect VMs {{ pdout.stdout }}"  
 