---

- hosts: cvms
  remote_user: nutanix
  gather_facts: no
  tasks:
    - name: get curator master
      shell: 'source /etc/profile.d/zookeeper_env.sh ; /usr/local/nutanix/bin/curator_cli get_master_location | grep -m 1 -E -o "(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\.(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\.(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\.(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)" '
      register: curator_cli_command
      run_once:  True
    - name: set curator master fact
      set_fact: curator_master={{ curator_cli_command.stdout }}
    - name: start curator full scan
      get_url: dest="/tmp/{{ curator_master }}_curator_scan_trigger_response.txt" url="http://{{ curator_master }}:2010/master/api/client/StartCuratorTasks?task_type=2" force="yes"
      delegate_to: "{{ curator_master }}"