---

- hosts: cvms
  gather_facts: no
  tasks:
    - name: get curator master
      shell: 'source /etc/profile.d/zookeeper_env.sh ; /usr/local/nutanix/bin/curator_cli get_master_location | grep -m 1 -E -o "(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\.(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\.(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\.(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)" ' 
      register: curator_cli_command
      run_once:  True
    - name: set curator master fact
      set_fact: curator_master={{ curator_cli_command.stdout }}
    - name: wait for Curator running jobs to be zero for 2 minutes 
      script: wait_curator_jobs_zero.sh 2
      delegate_to: "{{ curator_master }}"
    - name: wait for Chronos running jobs to be zero for 2 minutes 
      script: wait_chronos_jobs_zero.sh 2
      delegate_to: "{{ curator_master }}"
